### ISSUE TITLE
Please stop spamming everyone

### ISSUE THREAD

**Issue by MatthewEvans91** [jhadden04/lichess-ratings-to-openings-analysis#3]
https://www.reddit.com/r/learnprogramming/comments/pausqd/regarding_unsolicited_direct_messages_on/?sort=new

Your github has been reported.
Your udemy account has been reported.
We report every single reddit account you hijack.

Please stop spamming everyone across multiple subreddits, it is annoying.

I would have reached out through gmail, but your contact info on your GH main page just "How to reach me @gmail" which isn't terribly helpful.  The only other option is reaching out to you here or passing a message through your school.

**Comment by jhadden04** [comment]
yep
